spring.application.name=hookes-law
server.port=8080

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Devtools
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

# Logging
logging.level.com.example.hookeslaw=DEBUG